esphome:
  name: audio_sensor
  platform: ESP32
  board: nodemcu-32s

external_components:
  - source:
      type: git
      url: https://github.com/yourusername/esphome-audio-sensor
      ref: main  # or whatever branch/tag you want to use
    components: [ audio_sensor ]

wifi:
  ssid: "your_ssid"
  password: "your_password"

  ap:
    ssid: "Fallback Hotspot"
    password: "fallback_password"

api:
  services:
    - service: detect_washing_machine
      then:
        - lambda: 'id(audio_sensor).detect_washing_machine();'
    - service: detect_fire_alarm
      then:
        - lambda: 'id(audio_sensor).detect_fire_alarm();'
    - service: detect_dishwasher
      then:
        - lambda: 'id(audio_sensor).detect_dishwasher();'

ota:
logger:

web_server:
  port: 80

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14
  i2s_din_pin: GPIO32
  internal: true
  id: i2s_audio_input

custom_component:
  - lambda: |-
      auto audio_sensor = new AudioSensorComponent(id(i2s_audio_input));
      return {audio_sensor};
  - includes:
      - "audio_sensor/AudioSensorComponent.h"
