esphome:
  name: audio-sensor
  friendly_name: Audio Sensor
  #includes:
  #  - audio_sensor.h


esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/maddoglee/ESPHome-AudioSensor
      #ref: main
      #path: esphome/components
    components: [audio_sensor]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "6ZHTBgBqhr3egZ0qgybB34np+iqLCikhgWfFFYZBa/Q="
  services:
    - service: detect_washing_machine
      then:
        - lambda: 'id(audio_sensor).detect_washing_machine();'
    - service: detect_fire_alarm
      then:
        - lambda: 'id(audio_sensor).detect_fire_alarm();'
    - service: detect_dishwasher
      then:
        - lambda: 'id(audio_sensor).detect_dishwasher();'

ota:
  password: "cb8116576ebec27e0f541de93fc53acf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Audio-Sensor Fallback Hotspot"
    password: "fallback123"

web_server:
  port: 80

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO14
  #i2s_din_pin: GPIO32  # Corrected pin option
  id: i2s_audio_input

custom_component:
  - lambda: |-
      auto audio_sensor = new AudioSensorComponent(id(i2s_audio_input));
      return {audio_sensor};
    id: audio_sensor  # Ensure the ID is defined here
